### ISSUE TITLE
Sidebars should stay hidden when collapsed by the user

### ISSUE THREAD

**Issue by sambody** [mybuddymichael/obsidian-hide-sidebars-when-narrow#2]
I noticed a bug: it all works fine when both sidebars where open in the first place, but when one of the sidebars is collapsed by me (for example the right sidebar), and I resize the window even a little bit, the sidebar slides back in. But since I have collapsed it manually, I don't want it to appear at all when resizing, even when there is enough space. The same happens for both sidebars.

I expect it to remember that it was in a collapsed state, and stay collapsed. In other words, the action of automatically opening/closing of the sidebars should, in my opinion, only activate when the sidebars where open in the first place. Could you look into this?

Thanks, and have a good day.

**Comment by Maxlinn** [comment]
same wish, thanks for bringing this plugin after all : )

**Comment by NomarCub** [comment]
Another mechanism that could help with this, is not closing panes when the user is making the windows wider, to only close panes when the window is made narrower. Conversely, panes should be opened only when the window is made wider, not when made narrower. The size limit set should not matter in this, only when the thresholds are crossed in the right direction.

**Comment by NomarCub** [comment]
Hi!
I took over this plugin in a fork that you can find [here](https://github.com/NomarCub/obsidian-hide-sidebars-on-window-resize). Installed Obsidian plugins should auto-update to it automatically. The first release is basically the same, with the #5 proposal added that addresses this issue.

If this issue is still relevant to you, please submit it there too.
