### ISSUE TITLE
[FEATURE REQUEST] Hide when active leaf is `<length>` wide

### ISSUE THREAD

**Issue by firinael** [mybuddymichael/obsidian-hide-sidebars-when-narrow#3]
For auto hiding the sidebars when you vertically split a note, basically.

**Comment by ReaderGuy42** [comment]
Late to the game, but I agree, just wanted to ask about this too. Is this possible?

**Comment by NomarCub** [comment]
Hi!
I took over this plugin in a fork that you can find [here](https://github.com/NomarCub/obsidian-hide-sidebars-on-window-resize). Installed Obsidian plugins should auto-update to it automatically. The first release is basically the same, with the #5 proposal added that addresses #2.

If this issue is still relevant to you, please submit it there too.

**Comment by NomarCub** [comment]
My bad, issues weren't open on my repo for some reason. They are now.
