### ISSUE TITLE
[Feature Request] Hotkeys to Enable/Disable the feature

### ISSUE THREAD

**Issue by juicybox** [mybuddymichael/obsidian-hide-sidebars-when-narrow#4]
**Feature Request**
It would be great to have **hotkeys** to use them in macros/etc. to **disable** / **enable** the plugin features.

**Comment by NomarCub** [comment]
Hi!
I took over this plugin in a fork that you can find [here](https://github.com/NomarCub/obsidian-hide-sidebars-on-window-resize). Installed Obsidian plugins should auto-update to it automatically. The first release is basically the same, with the #5 proposal added that addresses #2.

If this issue is still relevant to you, please submit it there too.

**Comment by NomarCub** [comment]
My bad, issues weren't open on my repo for some reason. They are now.
